version: '3.2'

services:
    topteens_django:
      build: .  
      image: techvins/repo:topteens_django_dev
      working_dir: /app
      volumes:
        - "..:/app"
      deploy:
        placement:
          constraints:
            - "node.labels.name==manager1"
      environment:
        - "PYTHONUNBUFFERED=1"
        - "asdfasdf=1"
        # - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
    
    celery:
      image: techvins/repo:topteens_django_dev
      command: celery -A topteens worker -l info
      working_dir: /app
      environment:
        - "PYTHONUNBUFFERED=1"
        - "asdfasdf=1"
        # - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
    
    celery_beat:
      image: techvins/repo:topteens_django_dev
      command: celery -A topteens beat -l info
      working_dir: /app
      environment:
        - "PYTHONUNBUFFERED=1"
        - "asdfasdf=1"
        # - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
      

    tt_elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:7.14.2
        environment:
          - discovery.type=single-node
          - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
          - bootstrap.memory_lock=true
        deploy:
          placement:
            constraints:
              - "node.labels.name==manager1"
        volumes:
          - tt_elastic_volume:/usr/share/elasticsearch/data
    
    tt_redis:
      image: redis
        
volumes:
  tt_elastic_volume:

networks:
  default:
    external:
      name: techvins-network
